name: CI

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'
            - 'helm/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"

            - name: Install dependecies
              run: |
                python -m pip install pip --upgrade
                pip install -r rewuirements.txt

            - name: Run basic tests
              run: |
                python -m py_compile main.py
                echo "Compilation passed"

    push:
        runs-on: ubuntu-latest
        
        needs: build

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build & Push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo:${{ github.run_id }}